version: '3.8'

services:
  spring-app:
    build: .
    container_name: spring-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL: jdbc:oracle:thin:@190.150.10.103:1521/XEPDB1
      - SPRING_DATASOURCE_USERNAME: system
      - SPRING_DATASOURCE_PASSWORD: oracle
    restart: always
    